[package]
name = "pedro-app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Pedro desktop application."

[[bin]]
name = "pedro"
path = "src/main.rs"

[dependencies]
pedro-agent.workspace = true
pedro-core.workspace = true
pedro-pdf.workspace = true

anyhow.workspace = true
gpui.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

futures = "0.3"
image = "0.25"
time = "0.3"
